### ISSUE TITLE
Instantly crashes my game

### ISSUE THREAD

**Issue by kaydnshaw** [BobbyShmurner/HotSwappableMods#1]
I don’t know if you already know about this, but whenever I have this mod enabled it likes to crash my game on startup, I’ll attach a log when I get the chance to

**Comment by BobbyShmurner** [comment]
Thanks for the update!
There's gonna be a big update probably today or tomorrow, so if you wanna wait till the update that'd be great

Also sorry for the late response, i never check githubissues :/

**Comment by kaydnshaw** [comment]
Ah okie, I’ll wait till the update drops and update you then. Also it’s alright for you to respond late since you’re doing this in your own time, you’re not exactly forced to respond anyways

**Comment by BobbyShmurner** [comment]
Thanks for understanding xD
Ill need to just do some testing first, then it'll hopefully be up sometime in the next... 5 hours probably.

Ill close for now, but if the crash keeps occuring after the update, feel free to reopen and we'll continue this later

**Comment by kaydnshaw** [comment]
Didn’t expect you to respond that quick xD

**Comment by BobbyShmurner** [comment]
(i was actually on github, then i saw the notificcation lol)
